[build-system]
requires = ["asgiref",
    "autopep8",
    "Django==4.2",
    "pycodestyle",
    "pytz",
    "sqlparse",
    "Unipath",
    "dj-database-url",
    "python-decouple",
    "gunicorn==20.1.*",
    "whitenoise"
]
#build-backend = "poetry.core.masonry.api"

